### ISSUE TITLE
Make tests and docs push to private repos

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#114]
Sometimes the repos we push during CI stay there and they're not removed by the CI. This is not very crucial since another job periodically removes old stale CI repos. But they're listed and indexed to the public and they pollute the production space. Once #112 is fixed, we should make all CI repos private to avoid this issue.

**Comment by BenjaminBossan** [comment]
Despite merging #130, let's keep this open for now because the inference repos can't be set to private for now.

**Comment by adrinjalali** [comment]
Since we don't run the inference tests all the time, we significantly have fewer number of public repos from the CI. So I think we can close this one. I'm also not sure if/when we'll have private repo support on the inference side.
