### ISSUE TITLE
Have model cards

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#13]
We need to have model cards for everything that is about model reproduction but is not related to environment creation.

**Comment by adrinjalali** [comment]
Related to: https://github.com/nateraw/modelcards/issues/21

**Comment by merveenoyan** [comment]
Do we want to have a separate module that has saving related functions, given saving doesn't necessarily have to be related to HF Hub? If so, we will have to repeat the config writing and saving that is inside the` hf_hub`. I would rather have config writing and model card writing outside of the `hf_hub`. @adrinjalali

**Comment by merveenoyan** [comment]
Hyperparameters of a model/pipeline looks like [this](https://huggingface.co/merve/scikit-learn-hyperparams). (might've cheated a little from @ariG23498's vertical card lol hehe)

**Comment by adrinjalali** [comment]
Your link gives a 404 for me @merveenoyan

**Comment by adrinjalali** [comment]
I think we can close this one, the coming work is all improvements to what we have.
