### ISSUE TITLE
Secure persistence: Add examples

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#140]
Add examples of using secure persistence.

**Comment by adrinjalali** [comment]
doesn't #145 handle this as well? Or do you mean a more extended example?

**Comment by BenjaminBossan** [comment]
No, we should add something to https://github.com/skops-dev/skops/tree/main/examples and possibly also upload skops models to the Hub.

**Comment by adrinjalali** [comment]
@BenjaminBossan do you think we still need an example? I think we need more in detailed docs, but I'm not sure if we need an example for this. WDYT?

**Comment by BenjaminBossan** [comment]
I think this will be covered when we update existing examples, so a separate issue is not needed.
