### ISSUE TITLE
Add skops in config.json

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#146]
RE: https://github.com/huggingface/hub-docs/pull/314#issuecomment-1251060515 
Because as of now the models pushed using `skops` are `sklearn` models, we need to add an indicator in config.json that a given `sklearn` model is pushed through `skops`, to enable Hub specific features like deserialization snippets in repositories. WDYT? @BenjaminBossan

**Comment by osanseviero** [comment]
Maybe this could be automatically detected from the model card tags, as `skops` is added there automatically. https://huggingface.co/skops-ci/test-e5d99d15-cf1f-406f-a39e-81fb240dafae/blob/main/README.md#L5 

Alternatively, the existence of `config.model.file` + `sklearn` could be a very strong indicator it's a skop repo

**Comment by merveenoyan** [comment]
@osanseviero I thought of the latter instead as well.

**Comment by BenjaminBossan** [comment]
Maybe I'm missing something, but would it not be enough to check the file ending? `.pkl`, `.pickle` and `.joblib` are pickle files, `.skops` uses the new skops persistence format?

**Comment by merveenoyan** [comment]
@BenjaminBossan I think to include former repositories it makes sense to check the additional tags. I'll close this issue given we decided not to add anything else.
