### ISSUE TITLE
Secure persistence: Contiguity of arrays may change after loading

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#149]
After loading objects that contain numpy arrays, it can happen that the contiguity of the array is not the same as it was before saving. 

The current testing does not catch this but we could add more checks [here](https://github.com/skops-dev/skops/blob/005bb526466fdcb6c1aa223b77cab112f2a0d625/skops/io/tests/test_persist.py#L286):

```python
                assert val1.flags["C_CONTIGUOUS"] is val2.flags["C_CONTIGUOUS"]
                assert val1.flags["F_CONTIGUOUS"] is val2.flags["F_CONTIGUOUS"]
```

A peculiar things is that some of the arrays causing the error seem to be _neither_ C, nor Fortran contiguous. And the loaded array is _both_ C and Fortran contiguous. One example where this occurs is in `cv_results_` of `GrahpicalLassoCV`.

At least for performance reasons, it would be better to conserve the contiguity of the arrays. One approach could be to store the contiguity of the array in the `state` and then restore it after loading, although I don't know how to get an array with neither contiguity.

As for the other flags, I don't know how important they are and if ensuring that their values are conserved is feasible or even desirable.

**Comment by adrinjalali** [comment]
This should only be the case for object dtypes, since `npy` ensures the same contiguity.

We probably can do better in storing those numpy arrays anyway, something closer to the `npy` binary than what we have now.

**Comment by BenjaminBossan** [comment]
> This should only be the case for object dtypes, since `npy` ensures the same contiguity.

I haven't checked that. Anyway, should we consider this to be a bug?

> We probably can do better in storing those numpy arrays anyway, something closer to the `npy` binary than what we have now.

With "those", do you mean object arrays? Not sure how easy that would be.

**Comment by adrinjalali** [comment]
I think if the `npy` format is not keeping the contiguity, we can report it upstream, but for object arrays, we can find a better way to store them.

**Comment by BenjaminBossan** [comment]
I checked and it seems the issue is not that the dtype was object. E.g., for `GraphicalLassoCV`, we get the error on `cv_results_`, because `split_*_score` values change contiguity from neither C nor F, to both C and F. The dtype is `float64` and our `get_state` and `get_instance` methods save and load via numpy.

Interestingly, for the `mean_test_score`, we get no error -- it's both C and F contiguous before and after loading. So probably `np.save` and `np.load` work fine if the array is either C or F contiguous or both, but not if it's neither.

How we even get into this situation, I don't know.

**Comment by BenjaminBossan** [comment]
> What does it mean for a 2d array to not be C or F contiguous? Or are these 1d arrays that it doesn't matter whether they're C or F?

I checked, most arrays are 1d but there also arrays with shape (1, N), so technically 2d but practically 1d. I would assume that for those cases, the contiguity doesn't matter, but who knows if there are edge cases where it matters. For now, how about we add tests that check the contiguity, but only if `x.squeeze().ndim > 1`?

**Comment by adrinjalali** [comment]
That sounds good to me.
