### ISSUE TITLE
Mark persistence as experimental

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#153]
xref: https://github.com/skops-dev/skops/pull/145#discussion_r980237428

> 
> This folder:
> 
> [scikit-learn/scikit-learn@main/sklearn/experimental](https://github.com/scikit-learn/scikit-learn/tree/main/sklearn/experimental)
> 
> how it looks like from the user side:
> 
> [scikit-learn.org/stable/modules/generated/sklearn.model_selection.HalvingGridSearchCV.html#sklearn.model_selection.HalvingGridSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.HalvingGridSearchCV.html#sklearn.model_selection.HalvingGridSearchCV)

**Comment by BenjaminBossan** [comment]
Is this still relevant? Do we want to require adding an import like `from sklearn.experimental import enable_halving_search_cv` for `skops.io` to be activated?

**Comment by adrinjalali** [comment]
I would say yes. WDYT?

**Comment by BenjaminBossan** [comment]
I think it is less necessary here than in sklearn because skops is very new and it's more expected for things to change.

**Comment by adrinjalali** [comment]
Sure, I guess.
