### ISSUE TITLE
Test and integrate model cards from Hub library

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#155]
With the new release of `huggingface_hub` (https://github.com/huggingface/huggingface_hub/releases/tag/v0.10.0), model cards have been completely integrated there and `modelcards` is [deprecated](https://github.com/nateraw/modelcards#%EF%B8%8Fdeprecation-warning%EF%B8%8F-utils-in-this-repo-now-live-in-huggingface_hub).

From the skops side, we should ensure that everything works with the new hub version and write code to transition to using it instead of `modelcards`.

**Comment by adrinjalali** [comment]
we can migrate to using modelcards from huggingface_hub, and move the dependency up. I think we can do it since we still don't have many users.
