### ISSUE TITLE
Edit style of model plot to fit inside the model card 

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#164]
Model plot sometimes overflows if there are too many preprocessors.

 <img width="1360" alt="Ekran Resmi 2022-10-03 00 35 47" src="https://user-images.githubusercontent.com/53175384/193479325-84604631-79cc-450f-9192-42674503a768.png">

See more detailed explanation below: 
![Ekran Resmi 2022-10-06 16 50 02](https://user-images.githubusercontent.com/53175384/194345479-2cb7034c-5835-46b0-b9c0-d31023fe8d95.png)

**Comment by adrinjalali** [comment]
How is this a good first issue? I have no idea how to fix this lol

**Comment by merveenoyan** [comment]
@adrinjalali if you know front-end 😂 I think the top level container's class tag needs to include width and that's it. (not sure though)

**Comment by rushic24** [comment]
Where is it overflowing in the screenshot?

**Comment by merveenoyan** [comment]
@rushic24 the model plot above is overflowing from the model card (even covering the spaces that use this model section). We need to edit the top level container to have a width that would fit in model class. Can you handle it? This is easy if you know front-end well.

**Comment by merveenoyan** [comment]
@rushic24 you can edit the resulting plot, no?

**Comment by rushic24** [comment]
That's what I was going to check, can I have the overflow card snippet?

**Comment by rushic24** [comment]
Ok just found the resulting plot is editable, but I still feel this would be better if fixed in sklearn. I can try asking there and implement it here if they don't agree.

**Comment by rushic24** [comment]
It appears ok on a wide monitor LOL, any idea how can I replicate the bug on my system?
![image](https://user-images.githubusercontent.com/6279035/194342872-4a028ea3-576e-45a7-ace5-72f5000f78fe.png)

**Comment by merveenoyan** [comment]
@rushic24 I wanted to show the overflowing part below 👇 it happens on your monitor as well. The left part is model card, it's a markdown file. right part belongs to widget and links to spaces.
![Ekran Resmi 2022-10-06 16 50 02](https://user-images.githubusercontent.com/53175384/194345282-88ea4eef-5e78-4707-82b8-300ab04464ca.png)

**Comment by rushic24** [comment]
Ahh now I get it, then this isn't a sklearn issue.

**Comment by merveenoyan** [comment]
@rushic24 sorry for not communicating it well enough above, it looks a little cryptic 🥲

**Comment by rushic24** [comment]
Np! will a scrollbar like this work or we need to shrink it?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6279035/194462421-0c626927-a7a7-49ca-b280-235f77db8217.gif)

**Comment by adrinjalali** [comment]
Oh interesting, I like the scrollbar idea.

**Comment by merveenoyan** [comment]
@rushic24 it looks very cool!

**Comment by rushic24** [comment]
Is there a test UI like actual huggingface spaces?

**Comment by BenjaminBossan** [comment]
> Is there a test UI like actual huggingface spaces? The fix should work 🤞🏻

Can you just create a space and upload with the fixed code? That's probably easiest.

**Comment by merveenoyan** [comment]
@rushic24 given this is about model card README it would be nice to have a model with a lot of preprocessors in the pipeline (given it's making the plot bigger) inside a model repository rather than space.

**Comment by rushic24** [comment]
I'm still alive, sorry for being late. It does work :) 

I've added the exported README.md here with code
https://huggingface.co/rushic24/TestPlaygroundSkops

Will be back with some pytest+formatting
