### ISSUE TITLE
Make pytest fixtures atomic

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#166]
Some of the pytest fixtures are doing one too many things in model card tests. It would be more convenient if they were atomic. 
e.g.
```python
@pytest.fixture
def model_card_metadata_from_config(destination_path):
    X, y = load_iris(return_X_y=True, as_frame=True)
    est = LogisticRegression(solver="liblinear").fit(X, y)
    pkl_file = tempfile.mkstemp(suffix=".pkl", prefix="skops-test")[1]
    with open(pkl_file, "wb") as f:
        pickle.dump(est, f)
    hub_utils.init(
        model=pkl_file,
        requirements=[f"scikit-learn=={sklearn.__version__}"],
        dst=destination_path,
        task="tabular-classification",
        data=X,
    )
    card = Card(
        est, model_diagram=True, metadata=metadata_from_config(destination_path)
    )
    yield card
```
I had to rewrite this to make it work for tests with serializing with skops format.

**Comment by E-Aho** [comment]
Hey! I was thinking of picking this up

Might be useful to have a discussion about design decisions wrt testing on this but I'm happy to start on it :)

**Comment by adrinjalali** [comment]
@E-Aho could you please elaborate on the "testing philosophy"?

**Comment by E-Aho** [comment]
Ah sure, just things like how deep/thorough the tests should be, testing different edge cases/failure cases, that kind of thing.

Although I have reread the original post and this is more about adjusting already existing tests than writing new ones, so probably not needed on this issue.

**Comment by adrinjalali** [comment]
Yes, this one is a refactoring issue. So you wouldn't be touching test coverage.

We try to have an almost complete coverage on patches.
