### ISSUE TITLE
Add source links to the API docs

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#170]
It would be practical for the API docs to have links to the corresponding source code on GitHub, same as sklearn has.

**Comment by ayyucedemirbas** [comment]
Hi, I would like to contribute if you don't mind. However, I'm not sure what you mean when you say "adding source links to the API docs". Would you kindly be more specific? What I understand is, for instance, [this link](https://github.com/skops-dev/skops/blob/main/skops/hub_utils/_hf_hub.py) should be added to [this document](https://skops.readthedocs.io/en/latest/modules/classes.html#module-skops.hub_utils). Is that correct? Thank you so much!

**Comment by BenjaminBossan** [comment]
Yes, I think you got it. An example would be for sklearn's [`LinearRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html), there is the [`[source]`](https://github.com/scikit-learn/scikit-learn/blob/36958fb24/sklearn/linear_model/_base.py#L529) link on the top right which brings you to the source code of `LinearRegression` on GitHub.

The way to approach this is to have a [`linkcode_resolve`](https://smobsc.readthedocs.io/en/stable/usage/extensions/linkcode.html) function in the [conf.py](https://github.com/skops-dev/skops/blob/main/docs/conf.py). E.g. in sklearn, it's done [here](https://github.com/scikit-learn/scikit-learn/blob/14684bbae31918a394d61c75c23edee42d6c9761/doc/conf.py#L564-L570). There are probably a few more steps involved, it's been some time since I last worked on this.

**Comment by ayyucedemirbas** [comment]
Thank you so much for your help! I'll be working on it.

**Comment by ayyucedemirbas** [comment]
Would something like this work?

```
linkcode_resolve = make_linkcode_resolve(
    "skops",
    "https://github.com/skops-dev/"
    "skops/blob/main/skops/hub_utils/_hf_hub.py"
    "#L{lineno}",
)
```

Thanks!

**Comment by ayyucedemirbas** [comment]
Thank you so much for your help! 

I made [this](https://github.com/ayyucedemirbas/skops/blob/main/docs/conf.py). But, I get an error when I run pytest on both the original repo and my clone.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/8023150/193909699-1aa7e056-a117-4646-8399-c1b7258b47d5.png">

**Comment by adrinjalali** [comment]
Sorry my bad.

You can usually get the available commands by calling `make`. In this case, it'll hint you to call `make html`, which should work. And then you should be able to see the compiled files by looking at the `_build/html/index.html` file in a browser.

**Comment by ayyucedemirbas** [comment]
Oh, no problem

It also generates an error message:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/8023150/193920500-19d0fadf-26b2-49cc-ac90-df6fd6aeecd8.png">

**Comment by merveenoyan** [comment]
@ayyucedemirbas I will DM you the token and you can export it in CLI 🙂

**Comment by ayyucedemirbas** [comment]
Could you please take a look at [my PR](https://github.com/skops-dev/skops/pull/172/files)? Thanks a lot!
