### ISSUE TITLE
Toggles on the model plot in model repository doesn't work 

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#176]
The toggles on the model plot doesn't work. You can see an example [here](https://huggingface.co/brendenc/Fish-Weight).
The toggles should toggle (😂) and reveal information about their parameters.
<img width="337" alt="Ekran Resmi 2022-10-07 12 53 21" src="https://user-images.githubusercontent.com/53175384/194537329-0613f22d-2353-48e2-8f91-9fc07581d93b.png">

**Comment by adrinjalali** [comment]
Is that because the hub doesn't allow any js on the card?

**Comment by BenjaminBossan** [comment]
I noticed that too, but I swear that it used to work, at least sometimes.

**Comment by merveenoyan** [comment]
@BenjaminBossan same, it was okay. I'll ask someone on front-end team.

**Comment by merveenoyan** [comment]
Fixed on Hub side 🙂
