### ISSUE TITLE
Persistence: save to and load from str/bytes

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#180]
It would be nice to have the equivalent of `pickle.dumps` / `pickle.loads` or `json.dumps` / `json.loads` for `skops.save` / `skops.load`. That way, saving and loading does not necessarily require dealing with files. It could also facilitate testing and sending data over the wire.

**Comment by adrinjalali** [comment]
That makes sense, then we probably should also rename `save` to `dump` for consistency. I'm +1 on this.

**Comment by BenjaminBossan** [comment]
> then we probably should also rename `save` to `dump`

We can do that but I never liked the name "dump", it kinda has a negative connotation, doesn't it? Numpy also uses `save` and `load` but API-wise, we're closer to `pickle` and `json`, so I'm not sure.

**Comment by adrinjalali** [comment]
Since this should ideally be a replacement for `pickle`, I think following that API would make more sense.
