### ISSUE TITLE
AttributeError: module 'skops' has no attribute 'io'

### ISSUE THREAD

**Issue by rushic24** [skops-dev/skops#190]
On huggingface spaces there is a small button at the top, which says `</> use in scikit learn` 

And I think its showing some old syntax here which doesn't work.

![image](https://user-images.githubusercontent.com/6279035/196012327-5992af5e-f39e-47eb-a982-e263f5df7e60.png)

**Comment by adrinjalali** [comment]
@merveenoyan is this fixed now?

**Comment by merveenoyan** [comment]
This is the prerequisite #228

**Comment by merveenoyan** [comment]
I merged the PRs on Hub side, should be fixed with next deployment.

**Comment by adrinjalali** [comment]
Thanks @merveenoyan
