### ISSUE TITLE
Clarify expectations for new contributions

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#191]
Before making a contribution to skops, it is best to coordinate with the maintainers. So when picking an existing issue, that should be clarified. When working on something new, an issue should be opened first to discuss this. That way, we can avoid work being done unnecessarily.

This should be communicated in the `CONTRIBUTING.rst`. Possibly a PR template could also help, although it might be too late at that point.

**Comment by adrinjalali** [comment]
I agree, but I also worry that those people who send such PRs are the kind who also don't read contributing guidelines. But I'm happy to have something there.

**Comment by BenjaminBossan** [comment]
> but I also worry that those people who send such PRs are the kind who also don't read contributing guidelines

That might be the case for some, but there is only so much we can do to help. If it still happens, we can close the PR and refer to the guidelines.

**Comment by adrinjalali** [comment]
@BenjaminBossan you happy with what we have now or should we improve our contributing guideline?

**Comment by BenjaminBossan** [comment]
Yep
