### ISSUE TITLE
Consider running CI on different sklearn versions

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#192]
Follow up to this discussion: https://github.com/skops-dev/skops/pull/188#issuecomment-1280600073

We want to support multiple sklearn versions. Sklearn is an integral part of this library so we should ensure that skops works well with all supported versions. However, our CI only tests one version at the moment and it's unlikely that developers would test multiple versions locally. Therefore, it's easy to overlook errors caused by specific versions.

To help with this, CI should run on different sklearn versions. To not explode our test matrix, we may tie the sklearn version to the Python version, just as an example:

- Python 3.7 + sklearn 0.24
- Python 3.8 + sklearn 1.0
- Python 3.9 + sklearn 1.1
- Python 3.10 + sklearn main?

**Comment by adrinjalali** [comment]
that sounds reasonable to me.
