### ISSUE TITLE
Add style related info to CONTRIBUTING.rst

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#194]
I realized we need to almost always remind external contributors to run black on their code. It would be nice to add black (or extra note about pre-commit hooks) to contribution guidelines. I had to help an external contributor from DM because they didn't know what type of change does running black made on their code. (I guess people don't use the snippet to prepare the environment in CONTRIBUTING.rst or don't know what pre-commit hooks are for.

**Comment by adrinjalali** [comment]
we do have a note in contributing guidelines about pre-commit hooks. But we can make it more clear, and add it to the PR template as well maybe.

**Comment by BenjaminBossan** [comment]
+1 on being more explicit about black.

It seems, however, that people are not really following the CONTRIBUTING.rst :( We even have a link to it in the README.rst and the docs.

**Comment by adrinjalali** [comment]
pretty much nobody reads them ;)

**Comment by adrinjalali** [comment]
are we happy now? Anything we need to do for this issue?

**Comment by merveenoyan** [comment]
@adrinjalali it already exists in PR template, I say if we come across folks that still commit code that don't fit to style guide we can add to contributing.rst.
