### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#2]
Would be nice to have a logo for the project.

**Comment by koaning** [comment]
Maybe Mr. Skops? 

![image](https://user-images.githubusercontent.com/1019791/176718565-30f24ed5-fdfc-4d7d-8b69-95a01fae29d4.png)

It's a [villain](https://villains.fandom.com/wiki/Mr._Skops) from the Rayman video game saga.

**Comment by koaning** [comment]
You could photoshop it such that all of the bodyparts are made out of evil (non-hugging) emoji?

**Comment by BenjaminBossan** [comment]
Anyone got DALL-E 2 access?

**Comment by merveenoyan** [comment]
What we have atm 🌟
<img width="342" alt="Ekran Resmi 2022-07-13 18 45 20" src="https://user-images.githubusercontent.com/53175384/178787416-6e969853-4581-46d7-8a19-fb9c7ba7cb10.png">
<img width="736" alt="Ekran Resmi 2022-07-13 15 23 05" src="https://user-images.githubusercontent.com/53175384/178787425-91528020-d4d2-4e10-a276-c5117e2a6b62.png">

**Comment by merveenoyan** [comment]
@koaning I wanted to have a green background because it reminded me of pickle 😅 and @BenjaminBossan added orange in the middle which was more sklearn-y

**Comment by merveenoyan** [comment]
@adrinjalali those are Vincent's own project logos (the one you refer to is scikit-lego's logo 😅😂) I'm sorry we can't have that!

**Comment by adrinjalali** [comment]
haha, ok then, I'm easy on either versions, with or w/o the orange box.

**Comment by merveenoyan** [comment]
@adrinjalali @BenjaminBossan we need to pick :D 
![image](https://user-images.githubusercontent.com/53175384/179519337-ee6aaee0-a34c-42dd-9008-97ebe9af4837.png)
![image](https://user-images.githubusercontent.com/53175384/179519380-75f4e574-50c9-4b44-9366-d5bfdefb2229.png)
![image](https://user-images.githubusercontent.com/53175384/179519419-213019c4-7433-4943-b7ed-34aaae6f677c.png)
![skops (4)](https://user-images.githubusercontent.com/53175384/179520677-18b04fee-bb06-4306-8ad4-a778597ab1c0.png)
