### ISSUE TITLE
Add maintainers guide

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#217]
We should separate maintainers' and contributors' guide, and we can add this list as prefixes to commit titles: 

- DOC: documentation changes
- FEAT/FEA: new major features
- ENH: enhancements to existing features
- CI: continuous integration, sometimes overlaps with MNT
- MNT/MAINT: maintenance, technical debt, etc
- FIX: bug fixes
- TST: new tests, refactoring tests
- PERF: performance improvements

**Comment by BenjaminBossan** [comment]
(addendum from comment somewhere else: ENH should have user-facing implications)
