### ISSUE TITLE
Docs: Update persistence docs to reflect latest audit changes

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#220]
The [current persistence docs](https://github.com/skops-dev/skops/blob/ca9302146ce53cd89d73fc85d6ffb8143fa6d877/docs/persistence.rst) still reflect the state from before we added the audit feature. This should be updated soon, since we want people to test the feature and the documentation should be accurate for that.

**Comment by BenjaminBossan** [comment]
@adrinjalali will you take a stab at this, since you wrote the audit feature? If not, I can give it a try.

**Comment by adrinjalali** [comment]
Yes, it's on my list.
