### ISSUE TITLE
Add all scikit-learn estimators to the default trusted list

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#223]
We can read this list from `all_estimators` and trust them all. This doesn't include everything from sklearn, but is a good starting point and would substantially reduce the size of the `untrusted_types`, which would in turn make it easier for folks to notice malicious types in it.

We can probably read it dynamically from sklearn instead of hard coding it. Other installed/loaded packages might change the list, but if the user has some malicious packages installed, they're already compromised anyway.

**Comment by BenjaminBossan** [comment]
We can probably do some sanity checks, e.g. that they are all in `sklearn.*`, but that's of course not closing all gaps.

**Comment by EdAbati** [comment]
Hi, I would like to pick this up, if it's ok!
