### ISSUE TITLE
Drop python=3.7 support

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#245]
Now that colab supports 3.8, we should drop 3.7 support.

**Comment by BenjaminBossan** [comment]
I would be totally happy to drop it. Just wondering what our general policy should be about supported Python versions? For instance, 3.7's end of life is still [6 months away](https://peps.python.org/pep-0537/)

**Comment by adrinjalali** [comment]
Ideally we do what everybody else in the pydata stack does, the only reason we haven't done this is that Google Colab is crap.

**Comment by BenjaminBossan** [comment]
Yes, makes sense, especially since sklearn requires 3.8.
