### ISSUE TITLE
Forward compatibility of sklearn models saved with skops.io

### ISSUE THREAD

**Issue by tachukao** [skops-dev/skops#270]
Are sklearn models saved with skops.io forward compatible? For example, if I have a model trained and saved with sklearn 1.0, would it still work in sklearn 1.1?

**Comment by adrinjalali** [comment]
The format doesn't fix the forward compatibility issue. scikit-learn internals change quite often, and there's nothing we can do about that, and when they change, setting the attributes from the old model won't work for new models.

But we should add this to our documentation.

**Comment by tachukao** [comment]
@adrinjalali  thanks for the clarification!

**Comment by adrinjalali** [comment]
I think we can keep this issue open till we add it to our docs @BenjaminBossan
