### ISSUE TITLE
Annoyance with adding figures to model cards

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#300]
There is a small annoyance I found when adding figures to model cards. The problem is that the path to the file on the storage device and the path saved in the model card can differ. This can easily result in model cards references figures that it cannot find. Let me give an example:

I want to create a model card to upload it later to the HF Hub. For this, I create a temp folder and initialize a repo:

```python
hub_dir = Path(mkdtemp())
hub_utils.init(..., dst=hub_dir)
```

Then I create my model card and add a figure like so:

```python
model_card = card.Card(...)
fig_path = hub_dir / "my_plot.png"
fig.savefig(fig_path)
model_card.add_plot(**{"My beautiful plot": fig_path})
...
hub_utils.push(..., source=hub_dir)
```

The issue is that the plot is stored as `![My beautiful plot](/tmp/randomstr/my_plot.png)`, i.e. using its absolute path. When I now upload the model card to the Hub, the Hub will search for the plot in said temporary directory, which does not exist. On the Hub, what I actually want is to use the relative path, i.e., `![My beautiful plot](my_plot.png)`. But I cannot use the relative path instead of the absolute path either, because then the figure is not uploaded when calling, `hub_utils.push(..., source=hub_dir)`, since it's not in `hub_dir`, it is in my current working directory.

Now I can work around this by changing my code to

```python
model_card = card.Card(...)
fig.savefig(hub_dir / "my_plot.png")  # <= use abs path here
model_card.add_plot(**{"My beautiful plot": "my_plot.png"})  # <= use rel path here
```

but this is an ugly gotcha. Also, even though it will work correctly on the Hub, when I render the model card locally to preview it, it will fail because the paths mismatch.

Even worse, however, is when I want to add permutation importances. When I do

```python
pi = permutation_importance(model, X, y)
model_card.add_permutation_importances(pi, plot_file="my-permutation-importances.png", ...)
```

there will be a problem because the method stores the file locally using the `plot_file` argument, and it will use the same argument in the model card. If I put the relative path to `hub_dir` there, the file will not be found when the model card is rendered on the Hub. And when I put the relative path there, the file will not be included in the upload. The only solution is not to use `add_permutation_importances` but to create the figure by hand and call `add_plot` as discussed above, or I have to manually create a copy the file at the correct location.

I guess the problem could be avoided if the current working directory and the temporary directory for pushing are always identical, but requiring this is also annoying and I don't think we can assume it's always needed.

My guess why we haven't really encountered this problem yet is that in our examples, we either create model cards with plots but don't upload them to the Hub, or we do upload model cards to the Hub but they don't contain plots. We don't have an example that combines both (I'm working on exactly that, which is how I stumbled upon this).

Anyway, I don't have a solution to this problem. We can better document it and maybe warn users if a repo is created with a model card that references plots that are not inside the repo. But that's not very satisfying. Anyone got better ideas?

**Comment by BenjaminBossan** [comment]
Thinking a bit more about this, maybe the problem could be solved if the model card was aware that there is an associated repo. The repo path could be passed as an argument when initializing the model card. Then, each time a figure is added, the card could call `hub_utils.add_files` under the hood and strip the abs path from the figure link.

```python
hub_dir = Path(mkdtemp())
hub_utils.init(..., dst=hub_dir)
model_card = card.Card(..., repo_path=hub_dir)
model_card.add_plot(**{"My beautiful plot": "/path/to/my_plot.png"})

# under the hood, this calls
hub_utils.add_files("/path/to/my_plot.png", dst=repo_path) 
# and sets ![My beautiful plot](my_plot.png) in the model card
```

It's still not a perfect solution because the user needs to be pass the `repo_path` right from the start. They cannot start with creating the card and then create the repo later. Also, if they save the card in a different location than `hub_dir`, the links to the plots will be broken.

**Comment by BenjaminBossan** [comment]
Ah yes, some more minor annoyances:

* With `add_plot` and `add_permutation_importances`, it would be nice to have an optional `description` argument, for users who want to describe the figure more closely. Other methods like `add_metrics` and `add_getting_started_code` already provide a `description` argument, so having it would be more consistent too.
* With `add_permutation_importances`, its a bit annoying that the `plot_name` argument is used both for the title of the plot and the section. So it's impossible to have a title "Permutation Importances" but have the plot go to "Results/Permutation Importances". This could be solved by adding an optional `section` argument, that, if not set, defaults to `plot_name`, otherwise can be something completely different.

Note: If someone wants to work on these, I think they should be addressed in separate PRs, since they're orthogonal to the initial issue.

**Comment by lazarust** [comment]
Hey, @BenjaminBossan I can work on this! 

> They cannot start with creating the card and then create the repo later.

A couple of thoughts on this. Could we add a utility to create the repo for them? Then add a parameter on whether to create the repo or not. 

I think that solution would be better than just showing a warning.

For the other minor annoyances, should these be attached to different issues or just use this issue and multiple PRs?

**Comment by BenjaminBossan** [comment]
> Could we add a utility to create the repo for them? Then add a parameter on whether to create the repo or not.

Well, there is #207 going on, i.e. creating a README when initializing the repo instead of the other way round. I think that makes a bit more sense. But either way, it wouldn't solve the issue that if I start creating a model card, add a bunch of figures, etc., _then_ only do I think about creating a repo, it's too late. (To be clear, I'm thinking about a user who uses e.g. a Jupyter notebook and adds all that stuff progressively; in contrast, if the user writes a Python script, it wouldn't be too hard to change.)

> For the other minor annoyances, should these be attached to different issues or just use this issue and multiple PRs?

Personally, I don't care either way. Just note that the first point has its own issue now in #309 and #310 already takes care of addressing it.

**Comment by lazarust** [comment]
@BenjaminBossan Yeah, that makes sense to me. Should this wait until #207 is done?

> each time a figure is added, the card could call hub_utils.add_files under the hood

This sounds like a pretty good solution, does that sound good to you?

**Comment by BenjaminBossan** [comment]
> This sounds like a pretty good solution, does that sound good to you?

Honestly, I would hope there is a better solution. My issues are 1) if I call `add_plot`, it would be unexpected that a copy is created silently, and 2) if I later go and edit the original figure and overwrite it, the copy is not affected. Hopefully, we can come up with a better solution.

**Comment by adrinjalali** [comment]
I think it makes sense to copy the files, and if we're making that explicit enough, then there shouldn't be any surprises from the user. Like a `card.add_plot(file, path_in_repo)` kinda signature which would make it very clear that we're gonna do a copy.

**Comment by lazarust** [comment]
@adrinjalali and @BenjaminBossan Just to clarify, are we okay going forward with copying the files automatically?

**Comment by BenjaminBossan** [comment]
> Just to clarify, are we okay going forward with copying the files automatically?

I think you could give it a try and see how it goes. It's not a great solution but maybe there is no better way.

> Like a `card.add_plot(file, path_in_repo)` kinda signature which would make it very clear that we're gonna do a copy.

I agree that this would be more transparent but at the same time a bit annoying to do each time. If we initialize the model card with a `path_in_repo` argument, it could be copied automatically but then it's less obvious. Maybe we could have a `card.add_plot(..., copy="auto")` argument. If `card.path_in_repo` is `None` (default), nothing happens, if it is a str or path, the file is copied automatically, and if `copy=False`, nothing happens, even if there is a `path_in_repo`. WDYT?

**Comment by adrinjalali** [comment]
I don't think it's ever a good idea to not copy really. For the card to work, it needs to be copied with its corresponding images. However, we can allow users to add plots as base64, and allow them to render an html or pdf, which we can now do.  @lazarust I think it's easier to discuss details once we have a PR. It'd be nice if you could create a draft PR for us to discuss the details.

**Comment by lazarust** [comment]
@adrinjalali @BenjaminBossan sounds good! I'll try and get to this later this week or early next week
