### ISSUE TITLE
Ensure that all add_* methods on Card have a description keyword

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#309]
After the refactoring of model cards, some `add_*` methods got a `description` keyword to preserve feature parity with the previous implementation. Not all methods got this keyword, but it would be good to add it to all those methods. The reason is that it allows to get a result that is otherwise not easy to achieve and it is more consistent.

See also discussion [here](https://github.com/skops-dev/skops/pull/298#discussion_r1121462609).

**Comment by BenjaminBossan** [comment]
Oh, sorry, I added this with some other changes in #310, forgot to link this issue..

**Comment by adrinjalali** [comment]
Resolved in #310.
