### ISSUE TITLE
Document HF repo and config.json specs

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#33]
We should document what HF expects for a repo to be "valid" and for the widget to work, and also document what exactly goes into the `config.json` file.

I'll be working on this.

**Comment by BenjaminBossan** [comment]
> We should document what HF expects for a repo to be "valid" and for the widget to work, and also document what exactly goes into the `config.json` file.

Is there not something that we can link to, and only document the specifics for sklearn?

**Comment by adrinjalali** [comment]
I'm not sure, @osanseviero might know.

**Comment by osanseviero** [comment]
Nothing is enforced, we can have whatever we want in the `config.json`, there is no enforced schema in the Hub. E.g. SpeechBrain uses it to specify their interfaces (https://huggingface.co/speechbrain/tts-tacotron2-ljspeech/blob/main/config.json) while `transformers` has more info about the model + library version (https://huggingface.co/bert-base-uncased/blob/main/config.json)

**Comment by osanseviero** [comment]
The above is really a full template, but proper documentation is at https://huggingface.co/docs/hub/models-cards

**Comment by adrinjalali** [comment]
https://github.com/skops-dev/skops/pull/64 did this, and incremental improvements will come as we develop further.
