### ISSUE TITLE
CLI: Command to update a skops file

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#333]
The skops persistence format is updated over time, which may lead to bugs being fixed, performance being improved, reduced file size, etc. Therefore, as a user, I may want to upgrade my skops files periodically to ensure I can take advantage of the changes. Right now, I would need to do that manually but it would be nice for the skops CLI to offer this possibility.

Some optional features that come to mind:

- allow updating multiple files at once
- report if files where upgraded or nothing was changed
- some kind of check that upgraded file produces same object
- probably out of scope: upgrade to specified protcol version (or even downgrade)

**Comment by EdAbati** [comment]
Hi @BenjaminBossan , this sounds like a fun issue to work on. I can take it, if it's ok. 🙂

**Comment by adrinjalali** [comment]
@EdAbati sure, go for it :)

**Comment by EdAbati** [comment]
Hi both,
I finally had some time to have a look at this one (see #343) and I have a couple of questions regarding the optional points above:

>report if files where upgraded or nothing was changed

I thought we could compare the schemas (ignoring the `__id__` values since they are not deterministic). Is there anything else that could be updated/changed?

>some kind of check that upgraded file produces same object

I'm a bit unsure how we could do this. Maybe by allowing the user to provide some test data and checking that the predictions are the same? 🤔

**Comment by adrinjalali** [comment]
> I'm a bit unsure how we could do this. Maybe by allowing the user to provide some test data and checking that the predictions are the same? :thinking:

We should probably use `assert_params_equal` which we use in our tests already. WDYT @BenjaminBossan ?

> I thought we could compare the schemas (ignoring the __id__ values since they are not deterministic). Is there anything else that could be updated/changed?

Sounds about right.

**Comment by BenjaminBossan** [comment]
> We should probably use `assert_params_equal` which we use in our tests already.

That would be a possibility. Since it creates overhead, maybe it should be optional (could be added in a later PR too).
