### ISSUE TITLE
Setup release pipeline

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#34]
ATM we still don't have a release pipeline, it'd be nice to have an easy one like what @nateraw has in the https://github.com/nateraw/modelcards/ repo.

Do you have more experience with this @BenjaminBossan maybe?

**Comment by adrinjalali** [comment]
No I mean a github action which would build and push to `pypi`

**Comment by BenjaminBossan** [comment]
Ah, sorry, I completely misunderstood :D Yes, I can take a stab.

I think we can almost copy the [existing workflow](https://github.com/nateraw/modelcards/blob/main/.github/workflows/python-publish.yml). However, it's often recommended to first upload to https://test.pypi.org/ and check correctness there. Not sure if we can reflect that in a github action.

**Comment by adrinjalali** [comment]
Your GH action can take a string which can be `test` or `prod` for instance, and decide if it should upload to `test.pypi` or `pypi`

**Comment by BenjaminBossan** [comment]
Okay, got it. So that means there is no need for a separate workflow on creating a GH release.

**Comment by BenjaminBossan** [comment]
@adrinjalali I think this is done, right? If not, please re-open.
