### ISSUE TITLE
No module named skops.io 

### ISSUE THREAD

**Issue by aliceperin** [skops-dev/skops#371]
Hi, I'm trying to use a library that works with skops, but it doesn't load the model I need because skops.io seems not to be available.  I have the latest Python version 3.11 and a Mac. 

Please help :)

**Comment by adrinjalali** [comment]
Please update to the latest version, 0.7.post1, it's already fixed.

**Comment by aliceperin** [comment]
If I try to explicitly to update it to 0.7.post1 it says that the version doesn't exist (yet? I know you just released it ).

**Comment by adrinjalali** [comment]
Sorry, my bad, post0: https://pypi.org/project/skops/0.7.post0/
