### ISSUE TITLE
Can't Load Quantile Forest

### ISSUE THREAD

**Issue by brentonmallen1** [skops-dev/skops#383]
I'm currently using a Quantile Forest using the zillow library (https://github.com/zillow/quantile-forest/tree/efc1ebd08f1431a33532a418896cc14f22e22be3). I was able to dump the model just fine but am seeing an issue when attempting to load the model.  I've set the `trusted` parameter to true but I get the following error: 

```
ObjectNode._construct(self)
    408 cls = gettype(self.module_name, self.class_name)
    410 # Instead of simply constructing the instance, we use __new__, which
    411 # bypasses the __init__, and then we set the attributes. This solves the
    412 # issue of required init arguments. Note that the instance created here
    413 # might not be valid until all its attributes have been set below.
--> 414 instance = cls.__new__(cls)  # type: ignore
    416 if not self.children["attrs"]:
    417     # nothing more to do
    418     return instance

File quantile_forest/_quantile_forest_fast.pyx:568, in quantile_forest._quantile_forest_fast.QuantileForest.__cinit__()

TypeError: __cinit__() takes at least 2 positional arguments (0 given)
```

This seems to occur when attempting to instantiate the model type when validating/creating appropriate attributes: https://github.com/skops-dev/skops/blob/main/skops/io/_general.py#L414.  The model object type requires 2 positional arguments (https://github.com/zillow/quantile-forest/blob/efc1ebd08f1431a33532a418896cc14f22e22be3/quantile_forest/_quantile_forest_fast.pyx#L568) that aren't being passed in, and there seems to not be a straight forward way to pass them in.

I was wondering if there might be some workaround that I'm not seeing. At the very least, it seems unusual to allow for a model type to be dumped without validating that it can be opened.  Meaning, should the dump functionality check for this initialization before attempting to save in order to ensure the object that is being persisted can indeed be loaded.

**Comment by BenjaminBossan** [comment]
> At the very least, it seems unusual to allow for a model type to be dumped without validating that it can be opened. Meaning, should the dump functionality check for this initialization before attempting to save in order to ensure the object that is being persisted can indeed be loaded.

We have a very extensive test suite for sklearn and some external libraries that we support, which are documented. Therefore, those should always work, otherwise there is a bug.

Verifying that the dumped model can be loaded would add a cost to the process, so I wouldn't want to do that by default. However, I believe that having an option to verify the file optionally would be okay to have (would you be interested in implementing that feature?). As is, it's only one line of code, though, to test it yourself.

**Comment by brentonmallen1** [comment]
I can try to look into that when I have some time
