### ISSUE TITLE
Use a retry marker/decorator for tests

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#40]
Our tests fail sometimes since the backend errors when it should succeed, and usually running the tests again would solve the issue.

In `huggingface_hub` there is a decorator called [`retry_endpoint`](https://github.com/huggingface/huggingface_hub/blob/b6accae2ebfe2d0986934f2933b7bf2fb3811726/tests/testing_utils.py#L176) used in tests, and we can use the same thing. But we need to make it work with pytest fixtures and decorators (such as `pytest.mark.parameterize`) first.

There are some pointers on how to achieve this here: https://twitter.com/adrinjalali/status/1516346047156699138

**Comment by BenjaminBossan** [comment]
Maybe a naive question, but can we not just use [flaky](https://pypi.org/project/flaky/)?

**Comment by BenjaminBossan** [comment]
It has worked decently for me in the past. What could be missing for us is a backoff policy, but maybe we can live without that.

**Comment by adrinjalali** [comment]
yeah I'm happy with what it already has, it seems better than the `retry_endpoint` anyway.

**Comment by adrinjalali** [comment]
I'll be working on this.
