### ISSUE TITLE
Support for Numpy 2.0 and higher

### ISSUE THREAD

**Issue by batuhanfaik** [skops-dev/skops#425]
`numpy` version is not defined within `pyproject.toml` therefore installing `skops` in an environment with `numpy>=2` raises the following error:

```
AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
```

**Comment by adrinjalali** [comment]
Thanks for the report, will look into it.

**Comment by batuhanfaik** [comment]
Thanks a lot! @adrinjalali when can we expect a new release?
