### ISSUE TITLE
Suggestion: Add marker for slow tests

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#43]
Some tests take quite long to run. WDYT about adding a [marker for slow tests](https://docs.pytest.org/en/7.1.x/example/simple.html#control-skipping-of-tests-according-to-command-line-option)? Of course, in CI, we would always run the slow tests, but for local development, they will often be unnecessary.

**Comment by BenjaminBossan** [comment]
> and they make a bug chunk of tests

I would predict that this will change very soon but we can discuss it then.

**Comment by adrinjalali** [comment]
Probably a more meaningful one would be to mark tests which require internet.
