### ISSUE TITLE
Pandas: hard or soft dependency

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#53]
Right now in our CI we install `install` and `doc` dependencies, and the latter includes `pandas`.

However, we haven't assumed pandas as a hard dependency and users can use the library w/o having it installed.

https://github.com/skops-dev/skops/pull/45 for example, assumes it's okay for it not to be installed, if we want to go down this path, we should also test it, or we can make it an `install` dependency and assume it's always installed.

Which path should we take? We could also assume it a hard dependency now, and only make it soft later.

**Comment by BenjaminBossan** [comment]
Why is pandas a `doc` requirement? It doesn't seem to be used. If so, is it not easier to remove the dependency for now? We should probably have it as a `tests` dependency though, so we can check if data frames work as input.

**Comment by adrinjalali** [comment]
the docs use it with `as_frame=True`. If we want to test it, we should have some CI with and some CI w/o to make sure both work.

**Comment by BenjaminBossan** [comment]
> the docs use it with `as_frame=True`

Ah I see, that's easy to miss.

> If we want to test it, we should have some CI with and some CI w/o to make sure both work.

I think we should eventually test it. Probably there is a possibility to patch the import to make it act as if pandas were not installed.

**Comment by adrinjalali** [comment]
#98 tests this. Closing then. Keeping `pandas` as a soft dependency.
