### ISSUE TITLE
Implement __repr__ and __str__ for Card object

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#59]
The `Card` class doesn't implement string representation methods, and therefore the user doesn't see a nice view of the object when they print it.

It would be nice to have the methods implemented so that when users do `print(card)`, they see something other than the hash of the memory address of the object.

cc @merveenoyan

**Comment by BenjaminBossan** [comment]
I can also take this one. But let's wait until the #37 is merged.

**Comment by adrinjalali** [comment]
#68 has solved this.
