### ISSUE TITLE
Support more array-like and list-like string-like data

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#65]
https://github.com/skops-dev/skops/pull/45 introduces adding sample data to the config.json, but it only accepts ndarray/dataframe for arrays and a list of strings for text tasks.

We should support more data types, and convert them to what we can understand.

xref: https://github.com/skops-dev/skops/pull/45/files#r933221139

**Comment by anferico** [comment]
Hi, I would be interested in contributing to this. What additional data types are you planning to support exactly?

**Comment by BenjaminBossan** [comment]
See the comment linked above. So for example for text classification and text regression, we currently only allow lists of str, but scikit-learn is more flexible there, allowing, for instance, numpy arrays of strings, or iterables in general (that may not support indexing).

**Comment by adrinjalali** [comment]
We have something better now. Closing this and we can open specific issues once they occur.
