### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by BenjaminBossan** [skops-dev/skops#77]
When I evaluate whether to try a new library or framework, my first point of research is often the README, more so than the docs. Therefore, I believe we should have the main pieces of information at a glance in the README itself. Here are a few things I'd like to see, let me know what you think:

1. Description: It's currently empty. We could use a modified version from the first sentence, e.g. "skops helps you share your scikit-learn based models and put them in production"
2. A few sentences on what exactly skops can currently do to achieve that goal. Here I would also mention that at least for now, this is basically about integration with HF.
3. A small code snippet showing how it can be used in practice (self-contained would probably be too long, so maybe one where we assume the model has already been trained).
4. If it makes sense, some pics could be added, say, a screenshot of the model card on Hub.

**Comment by adrinjalali** [comment]
I"m not really a big fan of having documentation on the readme file though. I agree it can be expanded, but the idea is not that users should be able to jump into using the library by looking at the readme.

But I opened #80 to expand it a bit.

**Comment by BenjaminBossan** [comment]
> I'm not really a big fan of having documentation on the readme file though. I agree it can be expanded, but the idea is not that users should be able to jump into using the library by looking at the readme.

I guess you refer to point 3 about adding a code snippet? I see this as a trade-off. Yes, there is some redundancy, you have to keep it up to date etc. But just from personal experience, if I encounter a library I _might_ be interested in but the friction to figure out how to use it is too high, I will not follow up.

Right now, the friction is:

1. If I'm on the repo page, I have to find the documentation link
2. On the docs page, still no quick example.
3. So I need to find the examples and navigate there
4. Once there, I'm met with "walls of text" (6 and 5 pages on my browser window) because the examples are quite long.

I think I can agree with you on principle, but my prediction is that this principle will lead to potential users bouncing.

**Comment by adrinjalali** [comment]
I agree in principle, but I really have no idea how to include a small snippet which would make sense though. Happy to include it if you can come up with sth.
