### ISSUE TITLE
Create conda-forge feedstock

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#91]
We should add the package to conda-forge. Nothing to be done here in this repo, but an issue to keep track of it.

Docs: https://conda-forge.org/#add_recipe

**Comment by sugatoray** [comment]
I am working on this. Here's the PR.

- https://github.com/conda-forge/staged-recipes/pull/20031

**Comment by adrinjalali** [comment]
We have the package on conda-forge now :)
