### ISSUE TITLE
Take model as argument to generate the card

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#96]
About [this comment in this PR](https://github.com/huggingface/blog/pull/441/files#r943201153). Currently model card generation takes an argument called model which actually is a model path. We need to take model as well as model path, we can warn the user if both of them are missing.

**Comment by adrinjalali** [comment]
I don't think we need to change anything about the args, the `model` arg can take an estimator instance, or a path.

**Comment by p-mishra1** [comment]
@merveenoyan I created a PR regarding this #174 .
